#required to access object stores. 
#For GCP use HMAC(Hash-based Message Authentication Code) keys.
#For AWS use Access keys  
apiVersion: v1
kind: Secret
metadata:
  name: backup-creds
  namespace: tiledb-cloud
stringData:
  object_id:  QUtJQTJIWk5TQ0RESjZPTDJaM1kK   # required field to access object
  object_key: UzRpSUFEMHhLMGZOZGg0VUdKdFhzbldiN1FXZWRlRENEUHhUbmVLeQo= # required field to access object
