apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ebs-sc
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: ebs.csi.aws.com
parameters:
  type: gp2 # or gp3, io1, io2, sc1, st1
  fsType: ext4 # or xfs
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer

