apiVersion: k8s.mariadb.com/v1alpha1
kind: MariaDB
metadata:
  name: tile-mariadb
  namespace: tiledb-cloud
spec:
  image: docker-registry1.mariadb.com/library/mariadb:10.11.8
  rootPasswordSecretKeyRef:
    generate: false
    key: root-password
    name: tiledb-root
  nodeSelector:  #comment out below if not using specified nodes. Edit if using different labels.
    purpose: tiledb-core
  tolerations:
    - key: "purpose"
      operator: "Equal"
      value: "tiledb-core"
      effect: "NoSchedule"   
  port: 3306
  storage:
    size: 5Gi
  service:
    type: ClusterIP
  myCnf: |
    [mariadb]
    bind-address=*
    default_storage_engine=InnoDB
    binlog_format=row
    innodb_autoinc_lock_mode=2
    innodb_buffer_pool_size=1024M
    max_allowed_packet=256M
  metrics:
    enabled: true
  galera:
    enabled: true
    config:
      reuseStorageVolume: true
  replicas: 3
